### ISSUE TITLE
Error on Firmata install using the interchange

### ISSUE THREAD

**Issue by lynnaloo** [Makeblock-official/mbot_nodebots#12]
I can flash the board with Firmata using the Arduino IDE with no problem, but doesn't work using the interchange:

`interchange install git+https://github.com/Makeblock-official/mbot_nodebots -a uno --firmata=usb`

```
Retrieving manifest data from GitHub
Downloading hex file
found uno on port /dev/cu.wchusbserial1420
connected
reset complete.
flashing, please wait...
flash complete.
[Error: Sending 55000b20: receiveData timeout after 400ms]
```

Conversely, the Bluetooth flash using the interchange works great.

**Comment by ajfisher** [comment]
Is the Bluetooth module plugged in when you do it?

**Comment by lynnaloo** [comment]
Ah, should it be unplugged for both `--firmata=usb` and `--firmata=bluetooth`? I am only doing it for the latter.

**Comment by ajfisher** [comment]
In _theory_ the bluetooth module shouldn't be plugged in at all when you're
uploading a new firmware so it avoids conflicts...

**Comment by lynnaloo** [comment]
That did it for me. Thanks!
